apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: koku-metrics-operator
commonLabels:
  app: backup-to-bucket

resources:
  - cronjob.yaml

configMapGenerator:
  - name: backup-scripts
    files:
      - scripts/run-backup.sh
  - name: backup-config
    envs:
      - config.env

secretGenerator:
  - name: backup-credentials
    envs:
      - credentials.env
